version: '3.8'

services:
  confluence:
    image: atlassian/confluence-server:latest
    ports:
      - "8090"
    volumes:
      - type: volume
        source: confluence_data
        target: /var/atlassian/application-data/confluence
      - type: volume
        source: nfs_data
        target: /var/atlassian/application-data/confluence/shared-home
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/confluencedb
      - ATL_JDBC_USER=confluenceuser
      - ATL_JDBC_PASSWORD=P@ssw0rd
      - ATL_DB_TYPE=postgres72
    depends_on:
      db:
        condition: service_healthy
      nfs:
        condition: service_started
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 1m
      restart_policy:
        condition: on-failure