version: '3.8'
services:
  db:
    image: postgres:latest # Uses the latest PostgreSQL image
    environment:
    environment:
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rdP@ssw0rd
    # networks:
    #   - host
    volumes:
      - type: volume
        source: postgres_data # Mounts the PostgreSQL data volume
        target: /var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # Checks if PostgreSQL is ready
      interval: 30s # Runs the health check every 30 seconds
      timeout: 30s # Times out after 10 seconds
      retries: 10 # Retries 5 times before marking the service as unhealthy
