
services:
  jira-node2:
    image: atlassian/jira-software:latest
    links:
      - db
      - nginx
      - nfs
  
    expose:
      - 8080
    volumes:
      - type: volume
        source: jira_data2
        target: /var/atlassian/application-data/jira
      - type: volume
        source: nfs_data
        target: /var/atlassian/application-data/jira/shared-home
      # - ./jira-cacerts:/var/atlassian/application-data/jira/cacerts:rw
      # - ./jira-cacerts:/var/atlassian/application-data/jira/cacerts:rw
      # - ./jira-server.xml:/opt/atlassian/jira/conf/server.xml:ro
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/jiradb
      - ATL_JDBC_USER=jirauser
      - ATL_JDBC_PASSWORD=P@ssw0rd
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      - JVM_SUPPORT_RECOMMENDED_ARGS="-Dupm.plugin.upload.enabled=true  -Djira.downgrade.allowed=true"
      - CLUSTERED=true
      - JIRA_NODE_ID=jira-node2
      - EHCACHE_LISTENER_HOSTNAME=jira-node2
      - EHCACHE_LISTENER_PORT=40002
      - EHCACHE_OBJECT_PORT=40012
      - EHCACHE_PEER_DISCOVERY=default
      # - JIRA_NODE_ID
    # command: sh -c 'export JIRA_NODE_ID=$(hostname)'
    #   - EHCACHE_PEER_DISCOVERY=automatic
    #   - cacheManagerPeerProviderFactory=net.sf.ehcache.distribution.RMICacheManagerPeerProviderFactory
      # - JIRA_HOME=/opt/jira-home    
      - JIRA_SHARED_HOME=/var/atlassian/application-data/jira/shared-home
      - 'JVM_SUPPORT_RECOMMENDED_ARGS=-Djavax.net.ssl.trustStore=/var/atlassian/application-data/jira/cacerts'
      - HTTP_PROXY="http://localhost:80"
      
    depends_on:
    - jira
      

    entrypoint: >
      sh -c "
      chown -R 2001:2001 /var/atlassian/application-data/jira &&
      chown -R 2001:2001 /var/atlassian/application-data/jira/shared-home &&
      /entrypoint.py"
