
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    environment:
      - SHARED_DIRECTORY=/nfsshare
    volumes:
      - type: volume
        source: nfs_data
        target: /nfsshare
    # networks:
    #   - host
# networks:
#   host:
#     external: true
